name: Make Rulebook LaTeX PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", "tjs/pdf" ]

jobs:
  build:
    runs-on: docker.io/ts4z/debian-xetex-commonmark:733abc8
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: apt install -y texlive-xetex libcommonmark-perl
    - name: Make rulebook.pdf
      run: make rulebook.pdf
    - name: capture artifact
      run: mkdir pdf && mv rulebook.pdf pdf/barge-rulebook.pdf
    - name: deploy to ts4z.github.io
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: ts4z/ts4z.github.io
        publish_branch: main
        publish_dir: ./pdf
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        destination_dir: barge-rulebook/pdf
